version: "3.3"
services:
  dev:
    build:
      context: ./
      target: dev
    environment:
      TERM: xterm
    volumes:
      - .:/app
      - /app/node_modules
  app:
    build:
      context: ./
      target: app
    restart: always
