version: "3.3"
services:
  dev:
    build: .
    command: "npm run watch:dev"
    environment:
      TERM: xterm
    volumes:
      - .:/app
      - /app/node_modules
  app:
    build: .
    command: "npm run start"
    environment:
      TERM: xterm
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
