version: "3.4"
services:
  dev:
    build:
      context: ./
      target: dev
    environment:
      TERM: xterm
      SEND_SMS: "false"
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
  app:
    build:
      context: ./
      target: app
    environment:
      SEND_SMS: "true"
    network_mode: host
    restart: always
